kind: pipeline
name: default

steps:
- name: test
  image: java:openjdk-8
  commands:
  - GRADLE_USER_HOME=~/.gradle ./gradlew test
trigger:
  branch:
  - master
  event:
  - push
  - promote
  target:
  - production
